name: update-submodules
author: gendloop
description: 'update-submodules'
inputs:
  token:
      description: 'Personal token'
      required: true
      default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}

    - name: update-submodules
      shell: bash
      run: |
        # config
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config user.name
        git config user.email
        # update submodules to latest
        git submodule init
        git submodule update --remote
        # submit
        git add .
        (git commit -m "chore: update submodules") || true
        (git push) || true